# Generated by Django 5.0.6 on 2024-06-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horas',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='horas',
            name='prevision_paciente',
        ),
    ]
