# Generated by Django 5.0.6 on 2024-06-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='disponibilidad',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NODISPONIBLE', 'Nodisponible')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
