# Generated by Django 5.0.6 on 2024-06-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_horas_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='especialidad',
        ),
    ]
