# Generated by Django 5.0.6 on 2024-06-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_rut_medico_rut_medico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='medico',
            new_name='rut_medico',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='paciente',
            new_name='rut_paciente',
        ),
    ]
