# Generated by Django 5.0.6 on 2024-06-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_medico_reserva_rut_medico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='rut_medico',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='rut_paciente',
            new_name='paciente',
        ),
    ]
