# Generated by Django 5.0.6 on 2024-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_contacto_mensaje_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=7),
        ),
    ]
