# Generated by Django 5.0.6 on 2024-06-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reserva_fecha_alter_reserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=20),
        ),
    ]
